### PR TITLE
Set user entered text in local storage and set placeholder text

### PR DESCRIPTION
**Pull request by curranlipsett**
I don't have an account for makerlog, so I'm not able to test the clearing of local storage after login. I see no reason why it won't work though.

### CODE REVIEW

**Comment by fredddier** [comment]
Thanks, will test and review your commit.

**Comment by fredddier** [comment]
Hi @curranlipsett, and thank you for contributing. 

I've just tested your commit and there's some things that didn't worked as expected. 
- `userText` should be prefilled as input value, not a placeholder.
- Once logged in user should be able to post the task he was writing before, and once he clicks the "Add Task" button the `localStorage.userText` item should be removed.
- UI is not updating when user is logged in. (This can be fixed by moving [line 53](https://github.com/fredddier/atm/pull/8/commits/7e5fe4ac49a0ef5b29b37ba4b230b2410f672382#diff-c5e5c9f7d2ea648faea28f338649ca97R53) to the end of the `userToken` verification function).
- Express renders all the files inside the `public` folder as root files, so don't need to navigate to previous folders when referencing to them on index.html (`/index.js` it's ok).

Would you mind to check these changes and commit them to the PR?

**Comment by curranlipsett** [comment]
@fredddier thanks for the feedback - PR updated!

**Comment by fredddier** [comment]
Thank you for contributing @curranlipsett .

**Pull request merged**
